import type { Database } from './types';

export const mockDatabases: Database[] = [
  {
    id: 'db-1',
    Company: 'TechCorp',
    Location: 'New York',
    'Operational Status': 'Online',
    'Backed up': 'Yes',
    Contingency: 'Yes',
    Environment: 'Production',
    Critical: 'Yes',
    Monitored: 'Yes',
    'IP Address': '192.168.1.10',
    'Support Group': 'DBA Team A',
    'Name Instance': 'MSSQLSERVER',
    'BD Name': 'Sales_Prod',
    'Name Server': 'PROD-DB-01',
    'Is Clustered': 'No',
    Class: 'ERP',
    Edition: 'Enterprise',
    Engine: 'SQL Server 2019',
    License: 'Volume',
  },
  {
    id: 'db-2',
    Company: 'Innovate LLC',
    Location: 'London',
    'Operational Status': 'Online',
    'Backed up': 'Yes',
    Contingency: 'No',
    Environment: 'Development',
    Critical: 'No',
    Monitored: 'Yes',
    'IP Address': '10.0.0.25',
    'Support Group': 'Dev Team',
    'Name Instance': 'SQLEXPRESS',
    'BD Name': 'Dev_CRM',
    'Name Server': 'DEV-DB-01',
    'Is Clustered': 'No',
    Class: 'CRM',
    Edition: 'Developer',
    Engine: 'SQL Server 2022',
    License: 'Free',
  },
  {
    id: 'db-3',
    Company: 'DataSolutions',
    Location: 'Tokyo',
    'Operational Status': 'Offline',
    'Backed up': 'No',
    Contingency: 'No',
    Environment: 'Staging',
    Critical: 'No',
    Monitored: 'No',
    'IP Address': '172.16.5.100',
    'Support Group': 'QA Team',
    'Name Instance': 'MSSQLSERVER',
    'BD Name': 'Staging_Analytics',
    'Name Server': 'STG-DB-05',
    'Is Clustered': 'Yes',
    Class: 'Analytics',
    Edition: 'Standard',
    Engine: 'SQL Server 2017',
    License: 'SPLA',
  },
  {
    id: 'db-4',
    Company: 'TechCorp',
    Location: 'New York',
    'Operational Status': 'Online',
    'Backed up': 'Yes',
    Contingency: 'Yes',
    Environment: 'Production',
    Critical: 'Yes',
    Monitored: 'No',
    'IP Address': '192.168.1.11',
    'Support Group': 'DBA Team A',
    'Name Instance': 'PROD_INST_2',
    'BD Name': 'HR_Prod',
    'Name Server': 'PROD-DB-02',
    'Is Clustered': 'Yes',
    Class: 'HR',
    Edition: 'Enterprise',
    Engine: 'SQL Server 2019',
    License: 'Volume',
  },
  {
    id: 'db-5',
    Company: 'SecureBank',
    Location: 'Frankfurt',
    'Operational Status': 'Online',
    'Backed up': 'Yes',
    Contingency: 'Yes',
    Environment: 'Contingency',
    Critical: 'Yes',
    Monitored: 'Yes',
    'IP Address': '10.10.10.10',
    'Support Group': 'DR Team',
    'Name Instance': 'DR_CLUSTER',
    'BD Name': 'Finance_DR',
    'Name Server': 'DR-DB-CLUSTER',
    'Is Clustered': 'Yes',
    Class: 'Finance',
    Edition: 'Enterprise',
    Engine: 'SQL Server 2022',
    License: 'EA',
  },
];
