import type { Database } from './types';

export const mockDatabases: Database[] = [
  {
    id: 'db-1',
    nombre_bd: 'BD_Prueba',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-2',
    nombre_bd: 'BI_NUEVAPLATAFORMA',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-3',
    nombre_bd: 'COMISIONES',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-4',
    nombre_bd: 'consolidado_prod',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-5',
    nombre_bd: 'EMPYREC',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-6',
    nombre_bd: 'FB01_prod',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-7',
    nombre_bd: 'Gestion_LM',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-8',
    nombre_bd: 'GESTION_PROYECTO',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-9',
    nombre_bd: 'GestionComercial',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-10',
    nombre_bd: 'LHCAMARA',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-11',
    nombre_bd: 'RECAUDACIONDIARIAPREVIRED',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-12',
    nombre_bd: 'RECOMENDADOR',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-13',
    nombre_bd: 'TEST',
    instancia: 'MSSQLSERVER',
    servidor: 'CLH-COMISPRE-DB',
    ip: '10.81.233.20',
    motor: 'Microsoft SQL Server 2016',
    version: '13.3.6300.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'azure no-prod',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-14',
    nombre_bd: 'PREPAGO',
    instancia: 'MSSQLSERVER',
    servidor: 'clh-prepago-bd',
    ip: '10.85.11.52',
    motor: 'Microsoft SQL Server',
    version: '15.0.4312.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'GCP',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
  {
    id: 'db-15',
    nombre_bd: 'DBA_ADMIN',
    instancia: 'MSSQLSERVER',
    servidor: 'LH-BKPDBA',
    ip: '10.85.11.64',
    motor: 'Microsoft SQL Server',
    version: '15.0.4312.2',
    edicion: 'Standard',
    licencia: 'Standard Edition (64-bit)',
    ambiente: 'Production',
    critico: true,
    monitoreado: true,
    respaldo: true,
    contingencia: true,
    ubicacion: 'GCP',
    grupo_soporte: 'TIVIT',
    cluster: false,
    estado_operativo: 'Operational',
    compañia: 'Caja Los Heroes',
  },
];
