import type { Database } from './types';

export const mockDatabases: Database[] = [
  {
    "id": "db-new-1",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "BD_Prueba",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-2",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "BI_NUEVAPLATAFORMA",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-3",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "COMISIONES",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-4",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "consolidado_prod",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-5",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "EMPYREC",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-6",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "FB01_prod",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-7",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "Gestion_LM",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-8",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "GESTION_PROYECTO",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-9",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "GestionComercial",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-10",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "LHCAMARA",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-11",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "RECAUDACIONDIARIAPREVIRED",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-12",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "RECOMENDADOR",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-13",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.81.233.20",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "TEST",
    "Name Server": "CLH-COMISPRE-DB",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-14",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.52",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "PREPAGO",
    "Name Server": "clh-prepago-bd",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-15",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA_ADMIN",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-16",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA-LH",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-17",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA-LH_PERFMON-CLH-PREPAGO-BD",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-18",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA-LH_PERFMON-SETH-RBI-BD1",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-19",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA-LH_PERFMON-VMCONSOLBD03",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-20",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "DBA-LH-LogsApp",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-21",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "Gestion-TI",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-22",
    "Company": "Caja Los Heroes",
    "Location": "GCP",
    "Operational Status": "Online",
    "Backed up": "Yes",
    "Contingency": "Yes",
    "Environment": "Production",
    "Critical": "Yes",
    "Monitored": "Yes",
    "IP Address": "10.85.11.64",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "RespaldosREG",
    "Name Server": "LH-BKPDBA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-23",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "CLIENTES_FFNN_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-24",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "COMISIONQA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-25",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "ESTUDIOSCOMERCIALES_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-26",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "GESTIONCOMERCIAL_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-27",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "INCENTIVOS_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-28",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "LHCAMARA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-29",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "LHCAMARA_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  },
  {
    "id": "db-new-30",
    "Company": "Caja Los Heroes",
    "Location": "azure no-prod",
    "Operational Status": "Online",
    "Backed up": "No",
    "Contingency": "No",
    "Environment": "Staging",
    "Critical": "No",
    "Monitored": "Yes",
    "IP Address": "10.81.232.27",
    "Support Group": "TIVIT",
    "Name Instance": "MSSQLSERVER",
    "BD Name": "LH-GESTIONDOS2_QA",
    "Name Server": "LH-COMISDB-QA",
    "Is Clustered": "No",
    "Class": "",
    "Edition": "Standard",
    "Engine": "Microsoft SQL Server 2016",
    "License": "Standard Edition (64-bit)"
  }
]
