export type Database = {
  id: string;
  nombre_bd: string;
  instancia: string;
  servidor: string;
  ip: string;
  motor: string;
  version: string;
  edicion: string;
  licencia: string;
  ambiente: 'Production' | 'Development' | 'Staging' | 'Contingency' | 'QA' | 'TEST' | 'Produccion' | 'Noprod';
  critico: boolean;
  monitoreado: boolean;
  respaldo: boolean;
  contingencia: boolean;
  ubicacion: string;
  grupo_soporte: string;
  cluster: boolean;
  estado_operativo: 'Operational' | 'Online' | 'Offline' | 'Unknown' | 'Operacional';
  compañia: string;
};
